#! /bin/sh

# Not sure this is needed anymore as of Jan 2024)

##set -x

echo "Running 'aclocal' ..."
aclocal -I config

echo "Running 'autoheader' ..."
autoheader

##automake --foreign --add-missing --copy

echo "Running 'automake' ..."
automake --gnu --add-missing 

echo "Running 'autoconf' ..."
autoconf

## Possible alternative
## autoreconf -i

echo "done."

exit 1
