name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    permissions:
      contents: write
      issues: write
      pull-requests: write
      releases: write




    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool

      - name: Configure and build
        run: |
          ./configure
          make

      - name: Run tests
        run: |
          ./testing/pomdp-test

      - name: Extract version from source code
        id: version
        run: |
          version=$(grep -o 'VERSION "[^"]*"' src/version.h | cut -d'"' -f2)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create Release with Executable
        uses: softprops/action-gh-release@v1
        with:
          files: src/pomdp-solve
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
