name: Build and Release

on:
  push:
    branches:
      - main
      - '**' # Allows the workflow to run on all branches

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y autoconf automake libtool
          elif [ "${{ runner.os }}" = "macOS" ]; then
            brew install autoconf automake libtool
          fi

      - name: Configure and build
        run: |
          ./configure
          make

      - name: Run tests
        run: |
          ./testing/pomdp-test

      - name: Rename executable based on OS / architecture
        run: |
          mv src/pomdp-solve src/pomdp-solve-${{ runner.os }}.bin

      - name: Extract version from source code
        id: version
        run: |
          version=$(grep -o 'VERSION "[^"]*"' src/version.h | cut -d'"' -f2)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create Release with Executable
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src/pomdp-solve-ubuntu-latest.bin
            src/pomdp-solve-macos-latest.bin
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
